packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalogs:
  dev:
    '@antfu/eslint-config': ^4.13.0
    '@antfu/ni': ^24.3.0
    '@types/json-schema': ^7.0.15
    '@types/node': ^22.15.17
    bumpp: ^10.1.0
    eslint: ^9.26.0
    lint-staged: ^16.0.0
    pnpm: ^10.10.0
    simple-git-hooks: ^2.13.0
    tsx: ^4.19.4
    typescript: ^5.8.3
    unbuild: ^3.5.0
    vite: ^6.3.5
  prod:
    json-schema-to-typescript-lite: ^14.1.0
    ohash: ^2.0.11
  test:
    '@typescript-eslint/eslint-plugin': ^8.32.0
    eslint-plugin-antfu: ^3.1.1
    eslint-plugin-import-x: ^4.11.1
    eslint-plugin-jsx-a11y: ^6.10.2
    eslint-plugin-you-dont-need-lodash-underscore: ^6.14.0
    vitest: ^3.1.3
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
